### PR TITLE
Added cards with real fibonacci numbers

### PR DESCRIPTION
**Pull request by Kataklaus**
Added option to use cards with real fibonacci numbers. Although I can see the benefit of the modified fibonacci sequence, it doesn't help if the rest of the team insists on using the original fibonacci numbers during planning.

### CODE REVIEW

**Comment by mrclschstr** [comment]
Please merge? 😀 I'm struggling with the same issue right now, as my team insists to use the real fibonacci numbers.

**Comment by saschpe** [comment]
I'll try to roll a new release tomorrow, ok?

**Comment by mrclschstr** [comment]
Will you update the F-Droid version as well?

**Comment by saschpe** [comment]
I just published it on Google Play Store. I'll upload to F-Droid as well...

**Pull request merged**
